"""Apptainer experiment sandbox.

Runs agent-generated experiment code inside a prebuilt container image instead
of on the bare host — for host hygiene, reproducibility, and isolation of
untrusted/agent-generated code.

Enforcement is best-effort: a per-project ``sandbox/run.sh`` helper plus a
mandatory directive in the experimenter/coder prompts. If Apptainer or the base
image is missing, the helper falls back to bare-host execution so a run never
breaks. Hardening the untrusted lane to fail-CLOSED (refuse to run without the
sandbox) is a follow-up once the base image is guaranteed present on every node.
"""

from __future__ import annotations

import os
import shutil
from pathlib import Path
from typing import Optional

# Built once via `apptainer build` (see .ark/data/_sandbox/ark-sci.def). Override
# per-node with ARK_SANDBOX_SIF. Contains python3.12 + numpy/scipy/scikit-learn/
# pandas/matplotlib/statsmodels.
DEFAULT_SIF = "/data/fat/ark/ARK/.ark/data/_sandbox/ark-sci.sif"
APPTAINER_FALLBACK = "/data/secure/bin/apptainer"


def sandbox_sif_path() -> str:
    return os.environ.get("ARK_SANDBOX_SIF", DEFAULT_SIF)


def apptainer_bin() -> Optional[str]:
    found = shutil.which("apptainer")
    if found:
        return found
    if Path(APPTAINER_FALLBACK).exists():
        return APPTAINER_FALLBACK
    return None


def sandbox_available() -> bool:
    """True when both Apptainer and the base image are present on this node."""
    return bool(apptainer_bin()) and Path(sandbox_sif_path()).is_file()


_HELPER = r'''#!/bin/bash
# ARK experiment sandbox — AUTO-GENERATED by ark.sandbox. Runs a command inside
# the Apptainer base image with the project dir bind-mounted, isolated from the
# host $HOME. Fail-open: if apptainer/image is missing, runs on the host so a run
# never breaks (best-effort isolation).
set -uo pipefail
SIF="${ARK_SANDBOX_SIF:-__SIF__}"
APPTAINER="__APPTAINER__"
if command -v apptainer >/dev/null 2>&1; then APPTAINER="$(command -v apptainer)"; fi
PROJ="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
if [ "$#" -eq 0 ]; then echo "usage: sandbox/run.sh <command> [args...]" >&2; exit 2; fi
if [ ! -x "$APPTAINER" ] || [ ! -f "$SIF" ]; then
  echo "[sandbox] apptainer/image unavailable — running on host (NO isolation)" >&2
  exec "$@"
fi
# Persist extra pip installs across invocations via a host-side, bind-mounted dir.
mkdir -p "$PROJ/sandbox/pydeps"
export APPTAINERENV_PYTHONPATH="$PROJ/sandbox/pydeps:${PYTHONPATH:-}"
exec "$APPTAINER" exec --writable-tmpfs --no-home \
  --bind "$PROJ:$PROJ" --pwd "$PWD" \
  "$SIF" "$@"
'''


def write_sandbox_helper(code_dir) -> Optional[Path]:
    """Seed <code_dir>/sandbox/run.sh. Returns the path, or None if unavailable."""
    if not sandbox_available():
        return None
    code_dir = Path(code_dir)
    sdir = code_dir / "sandbox"
    sdir.mkdir(parents=True, exist_ok=True)
    helper = sdir / "run.sh"
    helper.write_text(
        _HELPER.replace("__SIF__", sandbox_sif_path()).replace("__APPTAINER__", apptainer_bin() or APPTAINER_FALLBACK)
    )
    helper.chmod(0o755)
    return helper


def experimenter_directive() -> str:
    """System-rule block mandating sandboxed experiment execution (empty if N/A)."""
    if not sandbox_available():
        return ""
    return (
        "\n\n## CRITICAL RULES — Experiment Sandbox (Apptainer)\n"
        "Run ALL experiment code inside the project's Apptainer sandbox, NOT on the "
        "bare host. Use the provided helper:\n"
        "    ./sandbox/run.sh python your_experiment.py\n"
        "    ./sandbox/run.sh bash your_script.sh\n"
        "The image has numpy, scipy, scikit-learn, pandas, matplotlib and statsmodels "
        "preinstalled (Python 3.12). Need another package? Install it into the "
        "bind-mounted deps dir so it persists across runs:\n"
        "    ./sandbox/run.sh pip install --target sandbox/pydeps <pkg>\n"
        "The project directory is bind-mounted at the same path, so files written to "
        "results/ or the workspace persist on the host. Do NOT run experiment code "
        "directly (e.g. bare `python exp.py`) — always go through ./sandbox/run.sh.\n"
    )
