apiVersion: v1
kind: LimitRange
metadata:
  name: ark-jobs-limits
  namespace: ark-jobs
spec:
  limits:
  - default:
      cpu: "4"
      memory: "16Gi"
    defaultRequest:
      cpu: "2"
      memory: "8Gi"
    type: Container
