"""add artifact table

Revision ID: 55e5ed2968ce
Revises: d9137d9946ea
Create Date: 2026-07-02 13:41:19.792078
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) render into revisions


# revision identifiers, used by Alembic.
revision: str = '55e5ed2968ce'
down_revision: Union[str, None] = 'd9137d9946ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('store_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_project_id'))

    op.drop_table('artifact')
    # ### end Alembic commands ###
