"""add projectstatedoc table

Revision ID: f1369e2c2a66
Revises: 55e5ed2968ce
Create Date: 2026-07-02 13:53:30.187801
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) render into revisions


# revision identifiers, used by Alembic.
revision: str = 'f1369e2c2a66'
down_revision: Union[str, None] = '55e5ed2968ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectstatedoc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projectstatedoc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projectstatedoc_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projectstatedoc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projectstatedoc_project_id'))

    op.drop_table('projectstatedoc')
    # ### end Alembic commands ###
