"""Capability wrappers — the 'B' layer: a pre-action gate at the tool boundary.

We place tiny shim executables (``rm``, ``sbatch``, ``gcloud``, …) at the FRONT
of the agent sandbox's ``PATH``. When the agent runs one, the shim runs instead
of the real binary; it phones home to the orchestrator (a file request the
``ApprovalWatcher`` answers), and only ``exec``s the real binary if the gate
allows. So a deletion / job-launch / push is genuinely held *before* it happens.

Design choices:

- **Dumb shim, smart watcher.** The shim does no risk logic — it always asks the
  watcher, which runs the real :class:`~ark.intervention.gate.Gate`. Allowed
  commands round-trip in milliseconds and never reach the human; only the
  policy's ``ask`` cases do. This keeps the shim dependency-free (stdlib only)
  and all policy in one place.
- **Fail-open.** If ``ARK_INTERVENTION_DIR`` is unset (interception not active),
  the shim immediately ``exec``s the real binary — wrappers never break a run.
- **Shadow, don't trust the prompt.** Because the shims share the real binary
  names and sit first on PATH, even a raw ``rm -rf`` the agent types hits the
  gate, not just a cooperative ``ark-rm``.
"""

from __future__ import annotations

import json
import os
import threading
import time
from pathlib import Path
from typing import Callable, Optional, Sequence


# Commands we shadow. Each maps to a risk the policy knows how to classify.
WRAPPED_EXES = (
    "rm", "rmdir", "shred",            # destructive_fs
    "sbatch", "srun", "qsub", "bsub",  # bulk_compute (jobs)
    "aws", "gcloud", "az",             # bulk_compute (cloud provision) + exfil (gsutil-ish)
    "scp", "rsync", "sftp",            # data_exfil
    # NOTE: `git` is intentionally NOT wrapped — agent git ops were too noisy.
    # ARK still gates its own autonomous push via classify_action("git_push").
)

_JOB_EXES = frozenset({"sbatch", "srun", "qsub", "bsub"})


# ── shim generation (orchestrator side, runs in the sandbox) ──

# Stdlib-only Python shim. {EXE} and {SHIM_DIR} are filled at install time.
_SHIM_TEMPLATE = '''#!/usr/bin/env python3
# AUTO-GENERATED by ark.intervention.wrappers — do not edit.
import json, os, sys, time, uuid

EXE = {EXE!r}
SHIM_DIR = {SHIM_DIR!r}

def _real_binary():
    """Find the real EXE on PATH, skipping our own shim dir."""
    for d in os.environ.get("PATH", "").split(os.pathsep):
        if not d or os.path.realpath(d) == os.path.realpath(SHIM_DIR):
            continue
        cand = os.path.join(d, EXE)
        if os.path.isfile(cand) and os.access(cand, os.X_OK):
            return cand
    return None

def _exec_real():
    real = _real_binary()
    if not real:
        sys.stderr.write("ark: real %r not found on PATH\\n" % EXE)
        sys.exit(127)
    os.execv(real, [EXE] + sys.argv[1:])

def main():
    base = os.environ.get("ARK_INTERVENTION_DIR")
    if not base:
        _exec_real()  # interception inactive → fail open
        return
    timeout = float(os.environ.get("ARK_INTERVENTION_TIMEOUT", "900"))
    req_dir = os.path.join(base, "requests")
    resp_dir = os.path.join(base, "responses")
    os.makedirs(req_dir, exist_ok=True)
    os.makedirs(resp_dir, exist_ok=True)
    rid = uuid.uuid4().hex
    payload = {
        "id": rid, "exe": EXE, "argv": [EXE] + sys.argv[1:],
        "cwd": os.getcwd(), "pid": os.getpid(), "ts": time.time(),
        "origin": os.environ.get("ARK_AGENT_TYPE", "agent"),
    }
    tmp = os.path.join(req_dir, rid + ".tmp")
    with open(tmp, "w") as f:
        json.dump(payload, f)
    os.replace(tmp, os.path.join(req_dir, rid + ".json"))

    resp_path = os.path.join(resp_dir, rid + ".json")
    deadline = time.time() + timeout
    while time.time() < deadline:
        if os.path.exists(resp_path):
            try:
                with open(resp_path) as f:
                    verdict = json.load(f).get("verdict", "deny")
            except Exception:
                verdict = "deny"
            try:
                os.remove(resp_path)
            except OSError:
                pass
            if verdict == "allow":
                _exec_real()
                return
            # Do NOT echo argv — it may contain secrets (curl -H <token>,
            # inline FOO=secret). The orchestrator log has the (redacted) detail.
            sys.stderr.write(
                "ark: BLOCKED by intervention policy. Do NOT retry this command — "
                "repeats are auto-denied. Work around it (e.g. write into a new "
                "directory instead of deleting) or continue without it.\\n")
            sys.exit(13)
        time.sleep(0.2)
    sys.stderr.write(
        "ark: approval timed out — %s was NOT run. Do NOT retry the same command "
        "(repeats are auto-denied); choose a different approach.\\n" % EXE)
    sys.exit(13)

if __name__ == "__main__":
    main()
'''


# Secret-request command (NOT a shadow of a real binary). Usage by the agent:
#   export HF_TOKEN=$(ark-request-secret HF_TOKEN "download gated dataset")
# It prints ONLY the value to stdout (so `export X=$(...)` keeps it out of logs).
_SECRET_SHIM = '''#!/usr/bin/env python3
# AUTO-GENERATED by ark.intervention.wrappers — do not edit.
import json, os, sys, time, uuid

def main():
    base = os.environ.get("ARK_INTERVENTION_DIR")
    if not base or len(sys.argv) < 2:
        sys.stderr.write("ark-request-secret: usage: ark-request-secret NAME [purpose]\\n")
        sys.exit(2)
    name = sys.argv[1]
    purpose = " ".join(sys.argv[2:]) if len(sys.argv) > 2 else ""
    timeout = float(os.environ.get("ARK_INTERVENTION_TIMEOUT", "1800"))
    req_dir = os.path.join(base, "requests"); resp_dir = os.path.join(base, "responses")
    os.makedirs(req_dir, exist_ok=True); os.makedirs(resp_dir, exist_ok=True)
    rid = uuid.uuid4().hex
    payload = {"id": rid, "type": "secret", "name": name, "purpose": purpose,
               "origin": os.environ.get("ARK_AGENT_TYPE", "agent"), "ts": time.time()}
    tmp = os.path.join(req_dir, rid + ".tmp")
    with open(tmp, "w") as f:
        json.dump(payload, f)
    os.replace(tmp, os.path.join(req_dir, rid + ".json"))
    resp_path = os.path.join(resp_dir, rid + ".json")
    deadline = time.time() + timeout
    while time.time() < deadline:
        if os.path.exists(resp_path):
            try:
                with open(resp_path) as f:
                    resp = json.load(f)
            except Exception:
                resp = {}
            try: os.remove(resp_path)
            except OSError: pass
            val = resp.get("value")
            if val:
                sys.stdout.write(val)   # value ONLY, no newline/label
                sys.exit(0)
            sys.stderr.write("ark-request-secret: denied\\n"); sys.exit(13)
        time.sleep(0.2)
    sys.stderr.write("ark-request-secret: timed out\\n"); sys.exit(13)

if __name__ == "__main__":
    main()
'''


def install_wrappers(shim_dir, exes: Sequence[str] = WRAPPED_EXES) -> Path:
    """Write shim executables into ``shim_dir`` and return it (to prepend to PATH).

    Idempotent: overwrites any existing shims. The caller is responsible for
    setting ``ARK_INTERVENTION_DIR`` (+ optionally ``ARK_INTERVENTION_TIMEOUT``,
    ``ARK_AGENT_TYPE``) in the sandbox env and putting ``shim_dir`` first on PATH.
    """
    shim_dir = Path(shim_dir)
    shim_dir.mkdir(parents=True, exist_ok=True)
    real_shim_dir = str(shim_dir.resolve())
    for exe in exes:
        content = _SHIM_TEMPLATE.replace("{EXE!r}", repr(exe)).replace(
            "{SHIM_DIR!r}", repr(real_shim_dir))
        path = shim_dir / exe
        path.write_text(content)
        path.chmod(0o755)
    # The secret-request command (not a shadow of a real binary).
    secret_path = shim_dir / "ark-request-secret"
    secret_path.write_text(_SECRET_SHIM)
    secret_path.chmod(0o755)
    return shim_dir


def sandbox_env(env: dict, intervention_dir, shim_dir, *, agent_type: str = "agent",
                timeout_seconds: int = 900) -> dict:
    """Return a copy of ``env`` with the shim dir first on PATH and the
    intervention vars set. Used when launching the agent."""
    env = dict(env)
    env["ARK_INTERVENTION_DIR"] = str(intervention_dir)
    env["ARK_INTERVENTION_TIMEOUT"] = str(timeout_seconds)
    env["ARK_AGENT_TYPE"] = agent_type
    prev = env.get("PATH", "")
    env["PATH"] = f"{str(shim_dir)}{os.pathsep}{prev}" if prev else str(shim_dir)
    return env


# ── watcher (orchestrator side) ────────────────────────────

class ApprovalWatcher:
    """Background thread bridging shim file-requests to the Gate.

    Polls ``<intervention_dir>/requests/``; for each request it runs the gate
    (which may prompt the human over Telegram) and writes the verdict to
    ``<intervention_dir>/responses/``. Tracks job-submission timestamps so the
    policy can detect bursts.
    """

    def __init__(self, intervention_dir, gate, work_dirs: Sequence[Path],
                 poll_interval: float = 0.25, log_fn: Optional[Callable] = None,
                 secret_sink: Optional[Callable] = None):
        self.dir = Path(intervention_dir)
        self.req_dir = self.dir / "requests"
        self.resp_dir = self.dir / "responses"
        self.gate = gate
        self.work_dirs = list(work_dirs or [])
        self.poll_interval = poll_interval
        self._log = log_fn or (lambda *a, **k: None)
        # Called with a granted secret value so it can be registered for
        # redaction (keeps the value out of subsequent logs).
        self._secret_sink = secret_sink
        self._stop = threading.Event()
        self._thread: Optional[threading.Thread] = None
        self._seen: set = set()
        self._job_times: list = []

    def start(self):
        self.req_dir.mkdir(parents=True, exist_ok=True)
        self.resp_dir.mkdir(parents=True, exist_ok=True)
        self._stop.clear()
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()

    def stop(self):
        self._stop.set()
        if self._thread:
            self._thread.join(timeout=3)
            self._thread = None

    def _run(self):
        while not self._stop.wait(self.poll_interval):
            try:
                self._drain()
            except Exception as e:
                self._log(f"  [intervention] watcher error: {e}", "WARN")

    def _drain(self):
        if not self.req_dir.exists():
            return
        for req in sorted(self.req_dir.glob("*.json")):
            if req.name in self._seen:
                continue
            self._seen.add(req.name)
            self._handle(req)

    def _recent_job_count(self, exe: str, window_seconds: int) -> int:
        if exe not in _JOB_EXES:
            return 0
        now = time.time()
        self._job_times = [t for t in self._job_times if now - t <= window_seconds]
        return len(self._job_times)

    def _handle(self, req_path: Path):
        try:
            data = json.loads(req_path.read_text())
        except Exception:
            return
        origin = data.get("origin", "agent")
        rid = data.get("id")

        if data.get("type") == "secret":
            # Fetch a secret VALUE from the human and hand it back to the shim.
            name = data.get("name", "?")
            value = self.gate.request_secret(name, data.get("purpose", ""), origin=origin)
            if value and self._secret_sink:
                try:
                    self._secret_sink(value)   # register for redaction
                except Exception:
                    pass
            self._write_response_dict(rid, {"value": value} if value else {"deny": True})
        else:
            argv = data.get("argv") or []
            exe = data.get("exe") or (argv[0] if argv else "")
            window = getattr(self.gate.policy, "job_window_seconds", 600)
            recent = self._recent_job_count(exe, window)
            allowed = self.gate.check_command(
                argv, work_dirs=self.work_dirs, recent_job_count=recent, origin=origin)
            if exe in _JOB_EXES and allowed:
                self._job_times.append(time.time())
            self._write_response_dict(rid, {"verdict": "allow" if allowed else "deny"})

        try:
            req_path.unlink()
        except OSError:
            pass
        # Drop the bookkeeping entry — the file is gone, so it won't be re-globbed.
        # Keeps _seen from growing without bound over a long run.
        self._seen.discard(req_path.name)

    def _write_response_dict(self, rid, payload: dict):
        if not rid:
            return
        tmp = self.resp_dir / f"{rid}.tmp"
        tmp.write_text(json.dumps(payload))
        os.replace(tmp, self.resp_dir / f"{rid}.json")
